service: gymondo-api

plugins:
  - serverless-dotenv-plugin

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:Scan"
            - "dynamodb:Query"
            - "dynamodb:BatchWriteItem"
          Resource: "arn:aws:dynamodb:us-east-1:479651470378:table/*"
        - Effect: "Allow"
          Action:
            - "s3:PutObject"
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - "Ref" : "ServerlessDeploymentBucket"
                - "/*"

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /users/create
          method: get
  getWorkouts:
    handler: workouts.get
    events:
      - httpApi:
          path: /workouts
          method: get
  getWorkoutById:
    handler: workouts.getById
    events:
      - httpApi:
          path: /workouts/{id}
          method: get
